version: '3'

services:
  client:
    build: .
    volumes:
      - "./assign1-react:/app"
    ports:
      - "80:3000"
    depends_on:
      - api

  api:
    build: .
    volumes:
      - "./assign1:/app"
    ports:
      - "3030:3030"